### ISSUE TITLE
How to config socket auth method?

### ISSUE THREAD

**Issue by irocnX** [v0l/socks5#1]
hello,
if I want to use username/password auth method, then How to config this socket option of auth for username and password?
such as,
  /// pass the socket to [SOCKSSocket]
  final proxy = SOCKSSocket(sock, auth: [AuthMethods.UsernamePassword]);

Thanks for reply!

**Comment by v0l** [comment]
Hi,

Sorry no auth methods are implemented yet, maybe this weekend i can do this if i find some time.

Sorry about that.

Regards,
Kieran

**Comment by irocnX** [comment]
Hello,

Thanks for your reply, look forward to see it ;-)

Regards,
Irocn

**Comment by v0l** [comment]
This is done now

**Comment by 0wzZZzz6** [comment]
how do I set the auth ?
