### ISSUE TITLE
get or post request.

### ISSUE THREAD

**Issue by jntagadiad** [v0l/socks5#2]
I have a authenticated proxy and managed a connection.

But the problem was I dont know how to set a get or post request using proxy.

**Comment by v0l** [comment]
A socks proxy simply accepts a command to connect to another server, this is only at the TCP layer not HTTP layer, Once you have request the socks proxy to connect to the remote server then you would simply issue an HTTP request on the same socket.

If you only need the socks proxy for HTTP it might be better if you try to use this: https://api.dart.dev/stable/2.9.3/dart-io/HttpClient/findProxy.html
